### ISSUE TITLE
学弟过来仰望大佬

### ISSUE THREAD

**Issue by Chuyuxuan0v0** [cloverzrg/go-portforwarder#1]
做完课设来gayhub上无聊的搜一搜项目，没想到直接看到同校的大佬，特别是看到大佬和同学把学校教务处给`请动了`  ,会心一笑，**这也是为学校数据安全做了贡献哈哈哈**，特来大佬最近最活跃的仓库提交issues表示仰慕。~~虽然可能方式不对哈哈~~  `献上膝盖哈哈`

**Comment by cloverzrg** [comment]
这个是fork的项目 https://github.com/HNUST-CS/myscore

**Comment by Chuyuxuan0v0** [comment]
> 这个是fork的项目 https://github.com/HNUST-CS/myscore

🤣
![](https://gitee.com/chuyuxuan/tuc/raw/master/laugh/104.gif)
